### PR TITLE
Add a review policy

### LINKED ISSUE #25: Review policy
What is the policy for reviewing changes to the spec?

### PR DESCRIPTION
**Pull request by ehuss**
This is an attempt to try to capture what I think should be guidelines for merging and reviewing, based on some of the discussion from the 2024-03-14 meeting.

I placed this within an outline of other team documentation I think we should have to give context to where it fits in. I expect to have these other sections filled in the future.

This explicitly does not cover how "final approval" is given by teams like the lang team, which I think will need a separate process.

Closes #25

### CODE REVIEW

**Review by JoelMarcey — APPROVED** [review]
This ironically, is a policy change PR that should be approved by the `t-spec` team without blocking changes 😊

**Comment by JoelMarcey** [comment]
@rfcbot poll "t-spec approve"

**Comment by JoelMarcey** [comment]
Maybe `rfcbot` doesn't fully work yet.

**Comment by ehuss** [comment]
@JoelMarcey You have to make sure the `T-spec` label is applied, otherwise rfcbot doesn't know which team to ping. Also, it can take ~10 minutes for it to respond since it is currently polling (once infra sets up the webhook, it should be immediate).

@rfcbot poll "t-spec approve"

**Comment by ehuss** [comment]
🤷 Bot now seems confused. Here are checkboxes:

* [ ] @JoelMarcey
* [x] @ehuss
* [ ] @m-ou-se
* [ ] @pnkfelix

**Pull request merged**
